#!/bin/sh

rsync -LH -trluhv --delete --stats --inplace \
    --exclude '.git' \
    ${SC:-$HOME/.local/scripts} $HOME/Dropbox/bak

rsync -LH -trluhv --delete --stats --inplace \
    --exclude '.git' \
    $HOME/.config/i3/ $HOME/Dropbox/bak/i3/

rsync -LH -trluhv --delete --stats --inplace \
    --exclude '.git' \
    $HOME/.dotfiles/ $HOME/Dropbox/bak/dotfiles/

cp -v $HOME/.local/bin/keeback $HOME/Dropbox/bak/scripts
cp -v $HOME/.config/rclone/rclone_func $HOME/Dropbox/bak/scripts
