#!/bin/sh

#
# scsh - screenshot
#

d="$(date +%Y%m%d)"
t="$(date +%H%M%S)"
s=$(xdg-user-dir PICTURES)/screenshots

[ -d $s ] || mkdir -p $s

f="$s/$d-$t.png"

# Send the grab directly to the clipboard
[ "$1" = "-c" ] && import -window root png:- | xclip -selection clipboard -t image/png && exit 0

# Grab an area of the screen
[ "$1" = "-a" ] && import png:- | xclip -selection clipboard -t image/png && exit 0

# Save screenshot on file
import -window root "$f"
