#!/bin/sh

option=$(echo -e "ﰸ Cancelar\n﫼 Salir\n Bloquear\nﰇ Reiniciar\n襤 Apagar" | dmenu -i -p "Selecciona una opción:")

case "$option" in
    "襤 Apagar") /usr/sbin/shutdown -h now ;;
    "ﰇ Reiniciar") /usr/sbin/shutdown -r now ;;
    " Bloquear") blur-lock.sh ;;
    "﫼 Salir") i3-msg exit ;;
    "ﰸ Cancelar"|*) exit ;;
esac
