#!/bin/sh

# 
# dpl - manage a YouTube playlist with dmenu
#

# Check dependencies
[ ! -x "$(command -v dmenu)" ] && echo "dmenu is not installed or executable." && exit 1
[ ! -x "$(command -v mpv)" ] && echo "mpv is not installed or executable." && exit 2
[ ! -x "$(command -v jq)" ] && echo "jq is not installed or executable." && exit 2

# Global variables
datadir="${XDG_DATA_HOME:-$HOME/.local/share}/dplaylist"
listfile="$datadir/vidlist"
logfile="/tmp/dplaylist_$(date "+%Y-%m-%d")"

[ -d "$datadir" ] || mkdir "$datadir"

# Main functions
checklist () {
    [ ! -s "$listfile" ] && echo -e "#!/bin/sh\n\ndeclare -A vidlist" > "$listfile"
}

add () {
    gettitle=$(curl -s https://www.youtube.com/oembed\?format\=json\&url\=$1 | jq '.title' | tr -d \")
    [ -z "$gettitle" ] && echo "No se ha podido obtener el título del vídeo." && exit 3
    sed -i "/^declare -A vidlist/a vidlist[$gettitle]=\"$1\"" "$listfile"
}

remove () {
    sed -i "/$1/d" "$listfile"
}

help () {
    cat << EOF

dplaylist - manage a playlist with dmenu

    Optional parameters:

    -a, --add: Add videos to the playlist
        Example: dpl -a https://youtu.be/jNQXAC9IVRw
    -r, --rm: Remove videos of the playlist specifying a pattern
        Example: dpl -r "Linux"
    -h, --help: Show this help.

EOF
}

main () {
    checklist
    . "$listfile"
    title=$(printf '%s\n' "${!vidlist[@]}" | dmenu -i -p "Selecciona que ver:" -l 20)
    if [ "$title" ]; then
        url=$(printf '%s\n' "${vidlist["${title}"]}")
        mpv --log-file="$logfile" $url
    else
        exit 0;    
    fi
}

case "$1" in
    -a|--add) add $2 ;;
    -r|--rm) remove $2 ;;
    -h|--help) help ;;
    *) main ;;
esac
